# Generated by Django 5.1 on 2024-08-31 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={'verbose_name_plural': 'Albums'},
        ),
        migrations.RenameField(
            model_name='albums',
            old_name='release_date',
            new_name='date',
        ),
    ]
